//
//  TabBarPresenter.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabBarPresentationLogic
{
  func presentSomething(response: TabBar.Something.Response)
}

class TabBarPresenter: TabBarPresentationLogic
{
  weak var viewController: TabBarDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TabBar.Something.Response)
  {
    let viewModel = TabBar.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
