//
//  FreeSMSViewController.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 26.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FreeSMSDisplayLogic: AnyObject {
    
    func displayLoad(viewModel: FreeSMS.FetchOptions.ViewModel)
    
    func displayError(errorMessage: String)
}

class FreeSMSViewController: UIViewController, FreeSMSDisplayLogic {
    func displayError(errorMessage: String) { }

    var interactor: FreeSMSBusinessLogic?
    var router: (NSObjectProtocol & FreeSMSRoutingLogic & FreeSMSDataPassing)?
    
    var mainView: FreeSMSView!
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
      
        
        self.view = mainView
        self.load()
        setupNavigationBar()
    }
    
    private func setupNavigationBar() {
        self.title = "Pulsuz SMS"
        
        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        let backButton = UIBarButtonItem()
        backButton.title = ""
        navigationController?.navigationBar.topItem?.backBarButtonItem = backButton
        appearance.backgroundColor = UIColor(.white)
        appearance.titleTextAttributes = [.foregroundColor: UIColor.black]
        navigationController?.navigationBar.standardAppearance = appearance
        if #available(iOS 15.0, *) {
            navigationController?.navigationBar.scrollEdgeAppearance = appearance
        }
    }
    
    
    // MARK: Load
    func load()
    {
        let request = FreeSMS.FetchOptions.Request()
        interactor?.fetchFreeSMS(request: request)
    }
    
    func displayLoad(viewModel: FreeSMS.FetchOptions.ViewModel) {
        self.mainView.dailySMSLimitView.configure(with: viewModel.model)
       
    }
    
    
}
