//
//  BalanceTransferModels.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

enum BalanceTransfer {
  // MARK: Use cases
  enum FetchOptions {
      
    struct Request {}
      
    struct Response {
        var balanceTransfer: BalanceTransferResponse
    }
      
    struct ViewModel {
        var balanceTransferDisplay: [String]
    }
  }
}
