//
//  BalanceTransferPresenter.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol BalanceTransferPresentationLogic {
    
    func presentTransferAmounts(response: BalanceTransfer.FetchOptions.Response)
    
    func presentError(error: Error)
}

class BalanceTransferPresenter: BalanceTransferPresentationLogic {
    
  weak var viewController: BalanceTransferDisplayLogic?
  
  // MARK: Presentation
    func presentTransferAmounts(response:  BalanceTransfer.FetchOptions.Response) {
        let viewModel = BalanceTransfer.FetchOptions.ViewModel(balanceTransferDisplay: response.balanceTransfer.amountList ?? [])
              viewController?.displayBalanceTransfer(viewModel: viewModel)
        }

        func presentError(error: Error) {
            viewController?.displayError(errorMessage: error.localizedDescription)
        }

}
