//
//  DummyInteractor.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DummyBusinessLogic
{
  func doSomething(request: Dummy.Something.Request)
}

protocol DummyDataStore
{
  //var name: String { get set }
}

class DummyInteractor: DummyBusinessLogic, DummyDataStore
{
  var presenter: DummyPresentationLogic?
  var worker: DummyWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Dummy.Something.Request)
  {
    worker = DummyWorker()
    worker?.doSomeWork()
    
    let response = Dummy.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
