//
//  DummyPresenter.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 25.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DummyPresentationLogic
{
  func presentSomething(response: Dummy.Something.Response)
}

class DummyPresenter: DummyPresentationLogic
{
  weak var viewController: DummyDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Dummy.Something.Response)
  {
    let viewModel = Dummy.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
