//
//  VASInteractor.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol VASBusinessLogic {
    func fetchVAS(request: VAS.FetchOptions.Request)
}

protocol VASDataStore { }

class VASInteractor: VASBusinessLogic, VASDataStore {
    
    var presenter: VASPresentationLogic?
    lazy var worker: VASWorkingLogic = VASWorker()
    
    var VASInfo: VASResponse?
    
    // MARK: Business Logic
    
    func fetchVAS(request: VAS.FetchOptions.Request) {
        self.worker.fetchVAS(completion:  { [ weak self] response in
            guard let self = self else { return }
            
            self.VASInfo = response
            if let VASInfo = self.VASInfo {
                let response = VAS.FetchOptions.Response(vasItems: VASInfo)
                self.presenter?.presentVAS(response: response)
            }
        })
        
    }
}
