//
//  VASModels.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

enum VAS {
    
  // MARK: Use cases
  enum FetchOptions {
      
    struct Request { }
      
    struct Response {
        let vasItems: VASResponse
    }
    struct ViewModel {
        let displayedItems: [VASModel]
    }
  }
}
struct VASModel {
    let title: String
    let desc: String
    let isSwitch: Bool
    let amountMonthly: String
    let amount: Double
    let renewal: String
    let renewalDate: String
    let nextRenewalDate: String
    let progressValue: Double
}
