//
//  VASPresenter.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol VASPresentationLogic {
    
  func presentVAS(response: VAS.FetchOptions.Response)
  
  func presentError(error: Error)
}

class VASPresenter: VASPresentationLogic {
 
  weak var viewController: VASDisplayLogic?
  
  // MARK: Do something
    func presentVAS(response: VAS.FetchOptions.Response) {
        let data = response.vasItems.data ?? []
        let models = data.map { item -> VASModel in
                return VASModel(
                    title: item.title ?? "",
                    desc: item.desc ?? "",
                    isSwitch: item.isSwitch ?? true,
                    amountMonthly: item.amountMonthly ?? "",
                    amount: item.amount ?? 0,
                    renewal: item.renewal ?? "",
                    renewalDate: item.renewalDate ?? "",
                    nextRenewalDate: item.nextRenewalDate ?? "",
                    progressValue: item.progressValue ?? 0
                )
            }
            let viewModel = VAS.FetchOptions.ViewModel(displayedItems: models)
            viewController?.displayLoad(viewModel: viewModel)
        }
    
   func presentError(error: Error) {
        viewController?.displayError(errorMessage: error.localizedDescription)
    }
}
