//
//  VASViewController.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VASDisplayLogic: AnyObject {
    
    func displayLoad(viewModel: VAS.FetchOptions.ViewModel)
    
    func displayError(errorMessage: String)
}

class VASViewController: UIViewController, VASDisplayLogic {
    
    var interactor: VASBusinessLogic?
    var router: (NSObjectProtocol & VASRoutingLogic & VASDataPassing)?
    var mainView: VASView?
    
    override func loadView() {
        super.loadView()
        self.view = mainView
    }

    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.load()
        self.view = mainView
        setupNavigationBar()
    }
    
    // MARK: Setup Navigation Bar
    private func setupNavigationBar() {
        self.title = "Əlavə dəyər xidmətləri"
        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        let backButton = UIBarButtonItem()
        backButton.title = ""
        navigationController?.navigationBar.topItem?.backBarButtonItem = backButton
        appearance.backgroundColor = UIColor(.white)
        appearance.titleTextAttributes = [.foregroundColor: UIColor.black]
        navigationController?.navigationBar.standardAppearance = appearance
        if #available(iOS 15.0, *) {
            navigationController?.navigationBar.scrollEdgeAppearance = appearance
        }
    }
    
 
    
    // MARK: Load
    func load(){
        self.mainView?.activityIndicator.startAnimating()
        let request = VAS.FetchOptions.Request()
        interactor?.fetchVAS(request: request)
    }
    
    func displayLoad(viewModel: VAS.FetchOptions.ViewModel) {
        mainView?.updateView(with: viewModel.displayedItems)
        self.mainView?.activityIndicator.stopAnimating()
        self.mainView?.callForwardView.isHidden = false
        self.mainView?.missedCallView.isHidden = false
        self.mainView?.secretNumberView.isHidden = false
        self.mainView?.unlimitedInternetUsageView.isHidden = false
    }
    
    func displayError(errorMessage: String) { }
}
