//
//  VASWorker.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol VASWorkingLogic {
    
    func fetchVAS(completion: @escaping (VASResponse) -> Void)
}

class VASWorker: VASWorkingLogic {
    // MARK: - Private Properties
    private let service: VASServiceProtocol = VASService()
    
    func fetchVAS(completion: @escaping (VASResponse) -> Void) {
        service.fetchVAS { result in
            switch result {
            case .success(let response):
                completion(response)
            default:
                print("no data")
            }
        }
    }
}
