//
//  DashboardModels.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

enum Dashboard
{
    // MARK: Use cases
    enum Load {
        struct Request { }
        
        struct Response { }
        
        struct ViewModel { }
    }
    
    enum FetchHubs {
        
        struct Request {}
        
        struct Response {
            let hubs: HubResponse
        }
        
        struct HubsModel {
            let hubs: [HubModel]
        }
    }
    
    enum FetchStories {
        struct Request { }
        
        struct Response {
            let stories: StoriesResponse
        }
        struct ViewModel {
            let stories: [StoryModel]
            
        }
    }
}

struct StoryModel {
    
    let id: Int
    let title: String
    let url: String
    var isSeen: Bool = false
}

struct HubModel {
    let id: Double
    let title: String
}


extension HubModel {
    var image : UIImage? {
        switch self.id   {
        case 1:
            return AppAssets.sms.load()
        case 2:
            return AppAssets.balance_transfer.load()
        case 3:
            return AppAssets.vas.load()
        case 4:
            return AppAssets.simcard.load()
        case 5:
            return AppAssets.credit.load()
        default:
            return nil
        }
    }
}
