//
//  DashboardWorker.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NarHubNetworkKit

protocol DashboardWorkerLogic {
    func fetchStories(_ completion: @escaping (StoriesResponse?) -> Void)
    
    func fetchHubs(_ completion: @escaping (HubResponse) -> Void)
}

class DashboardWorker: DashboardWorkerLogic {
    
    private let service = App.service
        
   // MARK: - Working Logic
    
   func fetchStories(_ completion: @escaping (StoriesResponse?) -> Void) {
       service.story.fetchStories { result in
            switch result {
            case .success(let data):
                completion(data)
            default:
                print("no data")
            }
        }
    }
    
    
    func fetchHubs(_ completion: @escaping (HubResponse) -> Void) {
//        service.hub.fetchHub { result in
//            switch result {
//            case .success(let response):
//                completion(response)
//            default:
//                print("no data")
//            }
//        }
    }
}
